### ISSUE TITLE
ImportError: /workspaces/BRNet/mmdet3d/ops/ball_query/ball_query_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv 

### ISSUE THREAD

**Issue by fathyshalaby** [cheng052/BRNet#9]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I tried running the demo mentioned in the readme.md and get the following error:

Traceback (most recent call last):
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_detector, show_result_meshlab
  File "/workspaces/BRNet/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import inference_detector, init_detector, show_result_meshlab
  File "/workspaces/BRNet/mmdet3d/apis/inference.py", line 8, in <module>
    from mmdet3d.core import Box3DMode, show_result
  File "/workspaces/BRNet/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/workspaces/BRNet/mmdet3d/core/bbox/__init__.py", line 2, in <module>
    from .coders import DeltaXYZWLHRBBoxCoder
  File "/workspaces/BRNet/mmdet3d/core/bbox/coders/__init__.py", line 6, in <module>
    from .class_agnostic_bbox_coder import ClassAgnosticBBoxCoder
  File "/workspaces/BRNet/mmdet3d/core/bbox/coders/class_agnostic_bbox_coder.py", line 4, in <module>
    from mmdet3d.core.bbox.structures import rotation_3d_in_axis
  File "/workspaces/BRNet/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/workspaces/BRNet/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/workspaces/BRNet/mmdet3d/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/workspaces/BRNet/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/workspaces/BRNet/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: /workspaces/BRNet/mmdet3d/ops/ball_query/ball_query_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=0 python demo/pcd_demo.py sunrgbd_000094.bin demo/brnet_8x1_sunrgbd-3d-10class.py checkpoints/brnet_8x1_sunrgbd-3d-10class_trained.pth
```
I used the config file included so don't think that is a solution to this problem.

**Comment by cheng052** [comment]
It's usually a compile error. You may check your pytorch version, nvcc version, gcc/g++ version for compiling the cuda ops in mmdetection3d.
